import { describe, expect, it } from 'vitest';
import { DEFAULT_MODEL_OPTIONS, modelOptionsFromProviderInfo } from './embedding-providers';

const noDownloadProvenance = {
    expectedSha256: null,
    expectedSizeBytes: null,
    spdxLicense: null,
    sourceRepo: null,
    modelCardUrl: null,
};

describe('embedding provider metadata', () => {
    it('maps backend provider metadata into selector options', () => {
        const options = modelOptionsFromProviderInfo([
            {
                id: 'clip',
                label: 'CLIP ViT-B/32',
                shortLabel: 'CLIP',
                modelName: 'clip-vit-b32',
                dimensions: 512,
                dimensionsLabel: '512d',
                scope: 'local',
                runtime: 'local-onnx',
                status: 'ready',
                available: true,
                downloadable: true,
                downloadLabel: 'Download CLIP (~350MB)',
                expectedSha256: 'c68d3d9a200ddd2a8c8a5510b576d4c94d1ae383bf8b36dd8c084f94e1fb4d63',
                expectedSizeBytes: 351686194,
                spdxLicense: 'MIT',
                sourceRepo: 'https://huggingface.co/Qdrant/clip-ViT-B-32-vision',
                modelCardUrl: 'https://huggingface.co/Qdrant/clip-ViT-B-32-vision',
                apiKeyProvider: null,
            },
            {
                id: 'gemini',
                label: 'Gemini Embedding 2',
                shortLabel: 'Gemini',
                modelName: 'gemini-embedding-2',
                dimensions: 3072,
                dimensionsLabel: '3072d',
                scope: 'cloud',
                runtime: 'cloud-api',
                status: 'key',
                available: false,
                downloadable: false,
                downloadLabel: null,
                ...noDownloadProvenance,
                apiKeyProvider: 'google',
            },
            {
                id: 'cohere',
                label: 'Cohere Embed v4 Multimodal',
                shortLabel: 'Cohere',
                modelName: 'cohere:embed-v4.0',
                dimensions: 1024,
                dimensionsLabel: '1024d',
                scope: 'cloud',
                runtime: 'cloud-api',
                status: 'key',
                available: false,
                downloadable: false,
                downloadLabel: null,
                ...noDownloadProvenance,
                apiKeyProvider: 'cohere',
            },
            {
                id: 'openai',
                label: 'OpenAI Text Embedding 3 Large',
                shortLabel: 'OpenAI',
                modelName: 'openai:text-embedding-3-large',
                dimensions: 3072,
                dimensionsLabel: '3072d',
                scope: 'cloud',
                runtime: 'cloud-api',
                status: 'key',
                available: false,
                downloadable: false,
                downloadLabel: null,
                ...noDownloadProvenance,
                apiKeyProvider: 'openai',
            },
            {
                id: 'ollama',
                label: 'Ollama Text Embeddings',
                shortLabel: 'Ollama',
                modelName: 'ollama:embeddinggemma',
                dimensions: 0,
                dimensionsLabel: 'model',
                scope: 'local',
                runtime: 'local-api',
                status: 'offline',
                available: false,
                downloadable: false,
                downloadLabel: null,
                ...noDownloadProvenance,
                apiKeyProvider: null,
            },
            {
                id: 'future-model',
                label: 'Future Model',
                shortLabel: 'Future',
                modelName: 'future-model',
                dimensions: 128,
                dimensionsLabel: '128d',
                scope: 'local',
                runtime: 'local-onnx',
                status: 'unsupported',
                available: false,
                downloadable: false,
                downloadLabel: null,
                ...noDownloadProvenance,
                apiKeyProvider: null,
            },
        ]);

        expect(options).toEqual([
            {
                id: 'clip',
                label: 'CLIP ViT-B/32',
                shortLabel: 'CLIP',
                modelName: 'clip-vit-b32',
                dims: '512d',
                scope: 'local',
                downloadLabel: 'Download CLIP (~350MB)',
            },
            {
                id: 'gemini',
                label: 'Gemini Embedding 2',
                shortLabel: 'Gemini',
                modelName: 'gemini-embedding-2',
                dims: '3072d',
                scope: 'cloud',
            },
            {
                id: 'cohere',
                label: 'Cohere Embed v4 Multimodal',
                shortLabel: 'Cohere',
                modelName: 'cohere:embed-v4.0',
                dims: '1024d',
                scope: 'cloud',
            },
            {
                id: 'openai',
                label: 'OpenAI Text Embedding 3 Large',
                shortLabel: 'OpenAI',
                modelName: 'openai:text-embedding-3-large',
                dims: '3072d',
                scope: 'cloud',
            },
            {
                id: 'ollama',
                label: 'Ollama Text Embeddings',
                shortLabel: 'Ollama',
                modelName: 'ollama:embeddinggemma',
                dims: 'model',
                scope: 'local',
            },
        ]);
    });

    it('keeps a complete static default for initial render', () => {
        expect(DEFAULT_MODEL_OPTIONS.map(option => option.id)).toEqual(['clip', 'dinov2', 'gemini', 'cohere', 'openai', 'ollama']);
    });
});
