import { beforeEach, describe, expect, it, vi } from 'vitest';
import { get } from 'svelte/store';
const mocks = vi.hoisted(() => ({ evaluateSmartCollection: vi.fn(), getBatchImages: vi.fn(), getImageCount: vi.fn(), listCollectionImages: vi.fn(), listImages: vi.fn(), listImagesByDetectedClass: vi.fn(), listImagesByFolder: vi.fn(), listImagesFiltered: vi.fn() }));
vi.mock('./api', () => mocks);
function image(id: string) { return { image: { id, sha256_hash: `hash-${id}`, width: 100, height: 100, format: 'png', file_size: 100, created_at: '2026-01-01', imported_at: '2026-01-01', ai_prompt: null, raw_metadata: null }, path: `/images/${id}.png`, thumbnail_path: null, selection: null, source_label: null, missing_at: null }; }
describe('rejected visibility image loading', () => {
    beforeEach(async () => { vi.clearAllMocks(); mocks.getImageCount.mockResolvedValue(1); mocks.listImages.mockResolvedValue([image('kept')]); mocks.getBatchImages.mockResolvedValue([image('batch-kept')]); const stores = await import('./stores'); stores.activeCollection.set(null); stores.activeDetectedClass.set(null); stores.activeFolder.set(null); stores.activeSmartCollection.set(null); stores.importBatchFilter.set(null); stores.importBatchImageIds.set([]); stores.minSizeFilter.set(0); stores.showMissing.set(false); stores.showRejected.set(false); });
    it('passes the visibility policy to library rows and counts', async () => { const stores = await import('./stores'); const loading = await import('./image-loading'); await loading.loadAllImages({ force: true, invalidateCache: true }); expect(mocks.listImages).toHaveBeenLastCalledWith(200, 0, false); expect(mocks.getImageCount).toHaveBeenLastCalledWith(false); stores.showRejected.set(true); await loading.loadAllImages({ force: true, invalidateCache: true }); expect(mocks.listImages).toHaveBeenLastCalledWith(200, 0, true); expect(mocks.getImageCount).toHaveBeenLastCalledWith(true); });
    it('keeps Current Import as the active scope while visibility changes', async () => { const stores = await import('./stores'); const loading = await import('./image-loading'); stores.importBatchFilter.set('batch-42'); await loading.loadImagesForCurrentScope({ force: true, invalidateCache: true }); expect(mocks.getBatchImages).toHaveBeenLastCalledWith('batch-42', false); expect(get(stores.images).map(item => item.image.id)).toEqual(['batch-kept']); stores.showRejected.set(true); mocks.getBatchImages.mockResolvedValue([image('batch-kept'), image('batch-rejected')]); await loading.loadImagesForCurrentScope({ force: true, invalidateCache: true }); expect(mocks.getBatchImages).toHaveBeenLastCalledWith('batch-42', true); expect(get(stores.importBatchFilter)).toBe('batch-42'); expect(get(stores.images).map(item => item.image.id)).toEqual(['batch-kept', 'batch-rejected']); });
});
