export function getFilename(path: string, fallback: string = 'image'): string {
    return path.split('/').pop() || fallback;
}

export interface ThumbnailAriaLabelInput {
    filename: string;
    rating: number;
    decision: string;
    sourceTag: string | null;
    selected: boolean;
    missing: boolean;
}

export function buildThumbnailAriaLabel(input: ThumbnailAriaLabelInput): string {
    const filename = input.filename || 'image';
    const safeRating = Number.isFinite(input.rating) ? Math.max(0, Math.round(input.rating)) : 0;
    const decision = input.decision || 'undecided';
    const sourceTag = input.sourceTag || 'unknown';
    const selected = input.selected ? 'selected' : 'not selected';
    const fileStatus = input.missing ? 'missing' : 'present';
    return `${filename}, rating ${safeRating}, decision ${decision}, source ${sourceTag}, ${selected}, ${fileStatus}`;
}

export function getThumbnailBorderClass(focused: boolean, selected: boolean): string {
    if (focused) return 'focused';
    if (selected) return 'selected';
    return '';
}

export function buildRangeSelectionIds<T>(
    items: T[],
    anchorIndex: number,
    targetIndex: number,
    getId: (item: T) => string
): Set<string> {
    if (items.length === 0) return new Set();

    const maxIndex = items.length - 1;
    const anchor = Number.isFinite(anchorIndex) ? clamp(Math.trunc(anchorIndex), 0, maxIndex) : 0;
    const target = Number.isFinite(targetIndex) ? clamp(Math.trunc(targetIndex), 0, maxIndex) : anchor;
    const start = Math.min(anchor, target);
    const end = Math.max(anchor, target);

    return new Set(items.slice(start, end + 1).map(getId));
}

export interface GridClickSelectionInput<T> {
    items: T[];
    selectedIds: Set<string>;
    focusedIndex: number;
    anchorIndex: number | null;
    targetIndex: number;
    shiftKey: boolean;
    toggleKey: boolean;
    getId: (item: T) => string;
}

export interface GridClickSelectionResult {
    selectedIds: Set<string> | null;
    anchorIndex: number;
}

function normalizeGridIndex(index: number | null, fallback: number, maxIndex: number): number {
    const value = index === null || !Number.isFinite(index) ? fallback : index;
    return clamp(Math.trunc(value), 0, maxIndex);
}

export function computeGridClickSelection<T>({
    items,
    selectedIds,
    focusedIndex,
    anchorIndex,
    targetIndex,
    shiftKey,
    toggleKey,
    getId,
}: GridClickSelectionInput<T>): GridClickSelectionResult {
    if (items.length === 0) {
        return { selectedIds: null, anchorIndex: 0 };
    }

    const maxIndex = items.length - 1;
    const target = normalizeGridIndex(targetIndex, 0, maxIndex);
    const anchor = normalizeGridIndex(anchorIndex, focusedIndex, maxIndex);

    if (shiftKey) {
        const rangeIds = buildRangeSelectionIds(items, anchor, target, getId);
        const next = new Set(selectedIds);

        if (toggleKey) {
            for (const id of rangeIds) {
                if (next.has(id)) {
                    next.delete(id);
                } else {
                    next.add(id);
                }
            }
        } else {
            for (const id of rangeIds) next.add(id);
        }

        return { selectedIds: next, anchorIndex: anchor };
    }

    if (toggleKey) {
        const item = items[target];
        const next = new Set(selectedIds);
        const id = getId(item);
        if (next.has(id)) {
            next.delete(id);
        } else {
            next.add(id);
        }
        return { selectedIds: next, anchorIndex: target };
    }

    return { selectedIds: null, anchorIndex: target };
}

export interface LoupeImagePathCandidate {
    path: string;
    thumbnail_path?: string | null;
}

const CULL_APP_DIR_SEGMENT = '/com.glebkalinin.cull/';
const CODEX_GENERATED_IMAGES_SEGMENT = '/.codex/generated_images/';

function normalizeAssetPath(path: string): string {
    return path.replace(/\\/g, '/');
}

export function isAssetProtocolSafePath(path: string | null | undefined): path is string {
    if (!path) return false;
    const normalized = normalizeAssetPath(path);
    return (
        normalized.includes(`${CULL_APP_DIR_SEGMENT}thumbnails/`) ||
        normalized.includes(`${CULL_APP_DIR_SEGMENT}generated/`) ||
        normalized.includes(CODEX_GENERATED_IMAGES_SEGMENT)
    );
}

/**
 * Thumbnail sizes generated by the Rust backend (src-tauri/src/db_core/thumbnails.rs).
 * The largest size is stored as the base `{id}.jpg`; smaller sizes are siblings
 * named `{id}_{size}.jpg`. Keep in sync with the Rust THUMBNAIL_SIZES array.
 */
export const THUMBNAIL_SIZES = [64, 128, 256, 800] as const;

export interface ThumbnailVariantOptions {
    /** Device pixel ratio; defaults to 1. */
    dpr?: number;
    /** Override the available sizes (mainly for tests). */
    availableSizes?: readonly number[];
    /** Clamp the effective dpr so retina does not always force the largest variant. */
    maxDprMultiplier?: number;
}

/**
 * Choose the smallest generated thumbnail variant whose pixel size is >= the on-screen
 * display size (times a clamped device pixel ratio). The largest size lives at the base
 * path `{id}.jpg`; smaller sizes are `{id}_{size}.jpg`. Any path that is not a
 * `{id}.jpg`/`.jpeg` filename is returned untouched so we never corrupt non-thumbnail paths.
 */
export function pickThumbnailVariant(
    basePath: string,
    displayPx: number,
    opts: ThumbnailVariantOptions = {}
): string {
    const sizes = [...(opts.availableSizes ?? THUMBNAIL_SIZES)].sort((a, b) => a - b);
    if (sizes.length === 0) return basePath;
    const largest = sizes[sizes.length - 1];

    // Only rewrite a trailing "{stem}.jpg" / "{stem}.jpeg" filename.
    const match = /^(.*\/)?([^/]+)(\.jpe?g)$/i.exec(basePath);
    if (!match) return basePath;

    const dpr = Number.isFinite(opts.dpr) && (opts.dpr as number) > 0 ? (opts.dpr as number) : 1;
    const cap = opts.maxDprMultiplier ?? 2;
    const effectiveDpr = Math.min(dpr, cap);
    const target = Math.max(0, displayPx) * effectiveDpr;

    const chosen = sizes.find((s) => s >= target) ?? largest;

    // The base file IS the largest variant; only smaller sizes get the `_{size}` suffix.
    if (chosen >= largest) return basePath;

    const prefix = match[1] ?? '';
    const stem = match[2];
    const ext = match[3];
    return `${prefix}${stem}_${chosen}${ext}`;
}

export interface PreviewPathOptions {
    /** On-screen display edge in CSS px. When set, a size-appropriate variant is chosen. */
    displayPx?: number;
    /** Device pixel ratio for variant selection. */
    dpr?: number;
}

export function safeAssetPreviewPath(
    image: LoupeImagePathCandidate,
    opts: PreviewPathOptions = {}
): string | null {
    if (isAssetProtocolSafePath(image.thumbnail_path)) {
        // Variant selection only applies to generated thumbnails, which have sibling sizes.
        if (opts.displayPx && opts.displayPx > 0) {
            return pickThumbnailVariant(image.thumbnail_path, opts.displayPx, { dpr: opts.dpr });
        }
        return image.thumbnail_path;
    }
    if (isAssetProtocolSafePath(image.path)) {
        // Original image file — no variants exist, so never rewrite it.
        return image.path;
    }
    return null;
}

export function chooseLoupeImagePath(
    image: LoupeImagePathCandidate,
    isRaw: boolean,
    sourceLoadFailed: boolean
): string | null {
    void isRaw;
    void sourceLoadFailed;
    return safeAssetPreviewPath(image);
}

export function computeGridLayout(
    containerWidth: number,
    thumbSize: number,
    gap: number,
    totalItems: number
): { cols: number; rows: number; cellSize: number; totalHeight: number } {
    const cols = Math.max(1, Math.floor((containerWidth + gap) / (thumbSize + gap)));
    const cellSize = thumbSize + gap;
    const rows = Math.ceil(totalItems / cols);
    const totalHeight = rows * cellSize;
    return { cols, rows, cellSize, totalHeight };
}

export interface VisibleItem {
    index: number;
    x: number;
    y: number;
}

export interface VisibleItemOptions {
    overscanRowsBefore?: number;
    overscanRowsAfter?: number;
}

function normalizeOverscanRows(value: number | undefined, fallback: number): number {
    if (value === undefined) return fallback;
    if (!Number.isFinite(value)) return fallback;
    return Math.max(0, Math.trunc(value));
}

export function computeVisibleItems(
    scrollTop: number,
    containerHeight: number,
    cols: number,
    cellSize: number,
    totalItems: number,
    options: VisibleItemOptions = {}
): VisibleItem[] {
    if (totalItems <= 0 || cols <= 0 || cellSize <= 0) return [];

    const firstVisibleRow = Math.max(0, Math.floor(scrollTop / cellSize));
    const visibleRowCount = Math.max(0, Math.ceil(containerHeight / cellSize));
    const overscanRowsBefore = normalizeOverscanRows(options.overscanRowsBefore, 0);
    const overscanRowsAfter = normalizeOverscanRows(options.overscanRowsAfter, 2);
    const rows = Math.ceil(totalItems / cols);
    const firstRenderedRow = Math.max(0, firstVisibleRow - overscanRowsBefore);
    const lastVisibleRow = Math.min(firstVisibleRow + visibleRowCount + overscanRowsAfter, rows);

    const items: VisibleItem[] = [];
    for (let row = firstRenderedRow; row < lastVisibleRow; row++) {
        for (let col = 0; col < cols; col++) {
            const index = row * cols + col;
            if (index >= totalItems) break;
            items.push({
                index,
                x: col * cellSize,
                y: row * cellSize,
            });
        }
    }
    return items;
}

export type ScrollDirection = 'up' | 'down' | 'none';

/**
 * Determine scroll direction with hysteresis: deltas smaller than `threshold` keep the
 * previous direction so jitter near zero does not flip the prefetch/overscan bias.
 */
export function computeScrollDirection(
    prevScrollTop: number,
    scrollTop: number,
    prevDirection: ScrollDirection,
    threshold = 4
): ScrollDirection {
    const delta = scrollTop - prevScrollTop;
    if (delta > threshold) return 'down';
    if (delta < -threshold) return 'up';
    return prevDirection;
}

export interface OverscanRows {
    before: number;
    after: number;
}

/**
 * Asymmetric overscan: render extra rows ahead in the travel direction (so scrolling never
 * reveals blanks) and fewer behind. `baseRows` is treated as at least 1.
 */
export function computeOverscan(direction: ScrollDirection, baseRows: number): OverscanRows {
    const base = Math.max(1, Math.trunc(baseRows) || 0);
    if (direction === 'down') return { before: 1, after: base * 2 };
    if (direction === 'up') return { before: base * 2, after: 1 };
    return { before: 2, after: base };
}

/**
 * Flat item indices for the rows just beyond the rendered window in the travel direction —
 * the "next screen" to decode-warm ahead of mounting. Distinct from the mounted window.
 */
export function computePrefetchIndices(
    scrollTop: number,
    containerHeight: number,
    cols: number,
    cellSize: number,
    total: number,
    direction: ScrollDirection,
    prefetchRows: number
): number[] {
    if (cols <= 0 || cellSize <= 0 || total <= 0 || prefetchRows <= 0) return [];

    const totalRows = Math.ceil(total / cols);
    const firstVisibleRow = Math.max(0, Math.floor(scrollTop / cellSize));
    const visibleRowCount = Math.max(0, Math.ceil(containerHeight / cellSize));

    let startRow: number;
    let endRow: number; // exclusive
    if (direction === 'up') {
        endRow = firstVisibleRow;
        startRow = Math.max(0, firstVisibleRow - prefetchRows);
    } else {
        // 'down' and 'none' both warm the rows below the visible window.
        startRow = firstVisibleRow + visibleRowCount;
        endRow = Math.min(totalRows, startRow + prefetchRows);
    }

    const indices: number[] = [];
    for (let row = startRow; row < endRow; row++) {
        if (row < 0 || row >= totalRows) continue;
        for (let col = 0; col < cols; col++) {
            const index = row * cols + col;
            if (index >= total) break;
            indices.push(index);
        }
    }
    return indices;
}

export function formatLoupeInfo(filename: string, width: number, height: number, format: string): string {
    return `${filename} | ${width}x${height} | ${format}`;
}

export function computeWheelZoom(
    currentScale: number,
    deltaY: number,
    min: number = 0.1,
    max: number = 20
): number {
    const factor = deltaY < 0 ? 1.15 : 1 / 1.15;
    return Math.max(min, Math.min(max, currentScale * factor));
}

export function computePanDrag(
    startPan: { x: number; y: number },
    startMouse: { x: number; y: number },
    currentMouse: { x: number; y: number }
): { x: number; y: number } {
    return {
        x: startPan.x + (currentMouse.x - startMouse.x),
        y: startPan.y + (currentMouse.y - startMouse.y),
    };
}

export interface RectLike {
    left: number;
    top: number;
    width: number;
    height: number;
}

export interface CropPoint {
    x: number;
    y: number;
}

export interface CropRect {
    x: number;
    y: number;
    width: number;
    height: number;
}

export interface CropSelectionPercent {
    left: number;
    top: number;
    width: number;
    height: number;
}

export type CropResizeHandle = 'n' | 's' | 'e' | 'w' | 'nw' | 'ne' | 'sw' | 'se';

function clamp(value: number, min: number, max: number): number {
    return Math.max(min, Math.min(max, value));
}

function cropRectFromSides(left: number, top: number, right: number, bottom: number): CropRect {
    return {
        x: Math.round(left),
        y: Math.round(top),
        width: Math.round(right - left),
        height: Math.round(bottom - top),
    };
}

export function clientToImagePoint(
    clientX: number,
    clientY: number,
    imageRect: RectLike,
    imageWidth: number,
    imageHeight: number
): CropPoint | null {
    if (imageRect.width <= 0 || imageRect.height <= 0 || imageWidth <= 0 || imageHeight <= 0) {
        return null;
    }

    const x = ((clientX - imageRect.left) / imageRect.width) * imageWidth;
    const y = ((clientY - imageRect.top) / imageRect.height) * imageHeight;

    return {
        x: clamp(x, 0, imageWidth),
        y: clamp(y, 0, imageHeight),
    };
}

export function cropRectFromImagePoints(
    start: CropPoint,
    end: CropPoint,
    imageWidth: number,
    imageHeight: number
): CropRect {
    const x1 = clamp(Math.min(start.x, end.x), 0, imageWidth);
    const y1 = clamp(Math.min(start.y, end.y), 0, imageHeight);
    const x2 = clamp(Math.max(start.x, end.x), 0, imageWidth);
    const y2 = clamp(Math.max(start.y, end.y), 0, imageHeight);

    return cropRectFromSides(x1, y1, x2, y2);
}

export function cropSelectionPercentFromImagePoints(
    start: CropPoint,
    end: CropPoint,
    imageWidth: number,
    imageHeight: number
): CropSelectionPercent | null {
    if (imageWidth <= 0 || imageHeight <= 0) return null;

    const x1 = clamp(Math.min(start.x, end.x), 0, imageWidth);
    const y1 = clamp(Math.min(start.y, end.y), 0, imageHeight);
    const x2 = clamp(Math.max(start.x, end.x), 0, imageWidth);
    const y2 = clamp(Math.max(start.y, end.y), 0, imageHeight);

    return {
        left: (x1 / imageWidth) * 100,
        top: (y1 / imageHeight) * 100,
        width: ((x2 - x1) / imageWidth) * 100,
        height: ((y2 - y1) / imageHeight) * 100,
    };
}

export function moveCropRect(
    rect: CropRect,
    deltaX: number,
    deltaY: number,
    imageWidth: number,
    imageHeight: number
): CropRect {
    const width = clamp(rect.width, 0, imageWidth);
    const height = clamp(rect.height, 0, imageHeight);

    return {
        x: Math.round(clamp(rect.x + deltaX, 0, imageWidth - width)),
        y: Math.round(clamp(rect.y + deltaY, 0, imageHeight - height)),
        width: Math.round(width),
        height: Math.round(height),
    };
}

export function resizeCropRectFromHandle(
    rect: CropRect,
    handle: CropResizeHandle,
    point: CropPoint,
    imageWidth: number,
    imageHeight: number,
    minSize: number = 1
): CropRect {
    let left = rect.x;
    let top = rect.y;
    let right = rect.x + rect.width;
    let bottom = rect.y + rect.height;

    const minWidth = Math.min(minSize, imageWidth);
    const minHeight = Math.min(minSize, imageHeight);

    if (handle.includes('w')) {
        left = clamp(point.x, 0, right - minWidth);
    }
    if (handle.includes('e')) {
        right = clamp(point.x, left + minWidth, imageWidth);
    }
    if (handle.includes('n')) {
        top = clamp(point.y, 0, bottom - minHeight);
    }
    if (handle.includes('s')) {
        bottom = clamp(point.y, top + minHeight, imageHeight);
    }

    return cropRectFromSides(left, top, right, bottom);
}
