use super::*;

#[tool_router(router = vision_router)]
impl CullMcp {
    #[tool(
        description = "Search for images containing a detected object class (e.g. 'person', 'car', 'dog'). Requires object detection to have been run."
    )]
    fn search_by_object(&self, Parameters(params): Parameters<SearchByObjectParams>) -> String {
        let state = self.app_handle.state::<AppState>();
        let limit = clamp_limit(params.limit.unwrap_or(50));
        match state.db.search_by_class(&params.class_name, limit * 2) {
            Ok(results) => {
                let r: Vec<serde_json::Value> = results.iter()
                .filter(|(id, _)| self.check_image_id_scope(id).unwrap_or(false))
                .take(limit as usize)
                .map(|(id, confidence)| {
                    serde_json::json!({"image_id": id, "confidence": confidence})
                }).collect();
                serde_json::to_string(&r).unwrap_or_else(|_| "[]".to_string())
            }
            Err(e) => format!("Error: {}", e),
        }
    }

    #[tool(
        description = "Get object detections for an image (bounding boxes, classes, confidence scores)"
    )]
    fn get_detections(&self, Parameters(params): Parameters<ImageIdParams>) -> String {
        match self.check_image_id_scope(&params.image_id) {
            Ok(false) => return "Error: Access denied — image outside token scope".to_string(),
            Err(e) => return format!("Error: {}", e),
            _ => {}
        }
        let state = self.app_handle.state::<AppState>();
        match state.db.get_detections(&params.image_id, None) {
            Ok(detections) => {
                serde_json::to_string(&detections).unwrap_or_else(|_| "[]".to_string())
            }
            Err(e) => format!("Error: {}", e),
        }
    }

    #[tool(
        description = "Get AI vision descriptions for an image (generated by Ollama vision models)"
    )]
    fn get_vision_metadata(&self, Parameters(params): Parameters<ImageIdParams>) -> String {
        match self.check_image_id_scope(&params.image_id) {
            Ok(false) => return "Error: Access denied — image outside token scope".to_string(),
            Err(e) => return format!("Error: {}", e),
            _ => {}
        }
        let state = self.app_handle.state::<AppState>();
        match state.db.get_vision_metadata(&params.image_id) {
            Ok(fields) => {
                let r: Vec<serde_json::Value> = fields.iter().map(|(key, value, source)| {
                serde_json::json!({"field": key, "value": value, "source": source})
            }).collect();
                serde_json::to_string(&r).unwrap_or_else(|_| "[]".to_string())
            }
            Err(e) => format!("Error: {}", e),
        }
    }

    #[tool(
        description = "Analyze blur, focus, and exposure for images. Returns a background job id."
    )]
    fn analyze_image_quality(
        &self,
        Parameters(params): Parameters<AnalyzeImageQualityParams>,
    ) -> String {
        if params.image_ids.is_empty() {
            return "Error: analyze_image_quality requires at least one image_id".to_string();
        }
        for image_id in &params.image_ids {
            match self.check_image_id_scope(image_id) {
                Ok(false) => {
                    return format!(
                        "Error: Access denied — image '{}' outside token scope",
                        image_id
                    )
                }
                Err(e) => return format!("Error: {}", e),
                _ => {}
            }
        }

        let state = self.app_handle.state::<AppState>();
        let total = params.image_ids.len() as u32;
        let (job_id, cancel_token) = state.jobs.create_job("quality", total);
        let job_id_ret = job_id.clone();
        let app = self.app_handle.clone();
        let image_ids = params.image_ids.clone();

        tauri::async_runtime::spawn(async move {
            let state = app.state::<AppState>();
            let mut analyzed = 0u32;

            for (i, image_id) in image_ids.iter().enumerate() {
                if cancel_token.is_cancelled() {
                    state.jobs.mark_cancelled(&job_id);
                    state.jobs.persist_terminal(&job_id, &state.db);
                    let _ = app.emit(
                        "job-status-changed",
                        serde_json::json!({"job_id": &job_id, "status": "cancelled"}),
                    );
                    return;
                }

                let ctx =
                    crate::services::ServiceContext::from_app_state(&state, Some(app.clone()));
                match crate::services::ai::analyze_image_quality(&ctx, image_id) {
                    Ok(_) => analyzed += 1,
                    Err(e) => {
                        crate::safe_eprintln!("Quality analysis error for {}: {}", image_id, e)
                    }
                }
                state
                    .jobs
                    .update_progress(&job_id, (i + 1) as u32, Some(image_id));
                let _ = app.emit(
                    "quality-progress",
                    serde_json::json!({
                        "job_id": &job_id,
                        "current": i + 1,
                        "total": total,
                        "analyzer": crate::db_core::quality::QUALITY_ANALYZER_VERSION,
                    }),
                );
            }

            state.jobs.complete(&job_id);
            state.jobs.persist_terminal(&job_id, &state.db);
            let _ = app.emit(
            "job-status-changed",
            serde_json::json!({"job_id": &job_id, "status": "completed", "processed": analyzed}),
        );
        });

        serde_json::json!({"job_id": job_id_ret, "total_images": total}).to_string()
    }

    #[tool(description = "Run YOLO object detection on images. Returns count processed.")]
    fn detect_objects(&self, Parameters(params): Parameters<DetectObjectsParams>) -> String {
        for image_id in &params.image_ids {
            match self.check_image_id_scope(image_id) {
                Ok(false) => {
                    return format!(
                        "Error: Access denied — image '{}' outside token scope",
                        image_id
                    )
                }
                Err(e) => return format!("Error: {}", e),
                _ => {}
            }
        }
        let state = self.app_handle.state::<AppState>();

        let variant = match params.variant.as_deref() {
            Some(v) => match crate::db_core::detection::YoloVariant::from_str(v) {
                Some(var) => var,
                None => {
                    return format!(
                        "Error: Invalid variant '{}'. Use 'nano', 'small', or 'medium'.",
                        v
                    )
                }
            },
            None => crate::db_core::detection::YoloVariant::Medium,
        };

        {
            let mut engine = state.detection_engine.lock();
            let needs_load = engine.session.is_none() || engine.loaded_variant != Some(variant);
            if needs_load {
                if !engine.is_variant_available(variant) {
                    return format!("Error: Model {} not downloaded", variant.model_name());
                }
                if let Err(e) = engine.load_yolo(variant) {
                    return format!("Error loading model: {}", e);
                }
            }
        }

        let total = params.image_ids.len() as u32;
        let (job_id, cancel_token) = state.jobs.create_job("detection", total);
        let job_id_ret = job_id.clone();
        let app = self.app_handle.clone();
        let image_ids = params.image_ids.clone();

        tauri::async_runtime::spawn(async move {
            let state = app.state::<AppState>();
            let mut detected = 0u32;

            for (i, image_id) in image_ids.iter().enumerate() {
                if cancel_token.is_cancelled() {
                    state.jobs.mark_cancelled(&job_id);
                    state.jobs.persist_terminal(&job_id, &state.db);
                    let _ = app.emit(
                        "job-status-changed",
                        serde_json::json!({"job_id": &job_id, "status": "cancelled"}),
                    );
                    return;
                }

                let id_refs: Vec<&str> = vec![image_id.as_str()];
                let images = match state.db.get_images_by_ids(&id_refs) {
                    Ok(imgs) => imgs,
                    Err(_) => {
                        state.jobs.update_progress(&job_id, (i + 1) as u32, None);
                        continue;
                    }
                };
                let img = match images.first() {
                    Some(img) => img,
                    None => {
                        state.jobs.update_progress(&job_id, (i + 1) as u32, None);
                        continue;
                    }
                };

                let engine = state.detection_engine.lock();
                match engine.detect(std::path::Path::new(&img.path)) {
                    Ok(detections) => {
                        drop(engine);
                        let _ =
                            state
                                .db
                                .store_detections(image_id, variant.model_name(), &detections);
                        detected += 1;
                    }
                    Err(e) => {
                        drop(engine);
                        crate::safe_eprintln!("Detection error for {}: {}", image_id, e);
                    }
                }
                state
                    .jobs
                    .update_progress(&job_id, (i + 1) as u32, Some(image_id));
                let _ = app.emit("detection-progress", serde_json::json!({"current": i + 1, "total": total, "model": variant.model_name()}));
            }

            state.jobs.complete(&job_id);
            state.jobs.persist_terminal(&job_id, &state.db);
            let _ = app.emit("job-status-changed", serde_json::json!({"job_id": &job_id, "status": "completed", "processed": detected}));
        });

        serde_json::json!({"job_id": job_id_ret, "total_images": total}).to_string()
    }

    #[tool(
        description = "Analyze images with Ollama vision model for natural language descriptions. Returns count processed."
    )]
    fn analyze_images(&self, Parameters(params): Parameters<AnalyzeImagesParams>) -> String {
        for image_id in &params.image_ids {
            match self.check_image_id_scope(image_id) {
                Ok(false) => {
                    return format!(
                        "Error: Access denied — image '{}' outside token scope",
                        image_id
                    )
                }
                Err(e) => return format!("Error: {}", e),
                _ => {}
            }
        }
        let state = self.app_handle.state::<AppState>();

        let url = state
            .db
            .get_setting("ollama_url")
            .unwrap_or(None)
            .unwrap_or_else(|| crate::db_core::vision::default_ollama_url().to_string());
        let model = state
            .db
            .get_setting("ollama_model")
            .unwrap_or(None)
            .unwrap_or_else(|| "minicpm-v".to_string());

        let total = params.image_ids.len() as u32;
        let (job_id, cancel_token) = state.jobs.create_job("vision", total);
        let job_id_ret = job_id.clone();
        let app = self.app_handle.clone();
        let image_ids = params.image_ids.clone();

        tauri::async_runtime::spawn(async move {
            let state = app.state::<AppState>();
            let mut analyzed = 0u32;

            for (i, image_id) in image_ids.iter().enumerate() {
                if cancel_token.is_cancelled() {
                    state.jobs.mark_cancelled(&job_id);
                    state.jobs.persist_terminal(&job_id, &state.db);
                    let _ = app.emit(
                        "job-status-changed",
                        serde_json::json!({"job_id": &job_id, "status": "cancelled"}),
                    );
                    return;
                }

                let id_refs: Vec<&str> = vec![image_id.as_str()];
                let images = match state.db.get_images_by_ids(&id_refs) {
                    Ok(imgs) => imgs,
                    Err(_) => {
                        state.jobs.update_progress(&job_id, (i + 1) as u32, None);
                        continue;
                    }
                };
                let img = match images.first() {
                    Some(img) => img,
                    None => {
                        state.jobs.update_progress(&job_id, (i + 1) as u32, None);
                        continue;
                    }
                };

                let path = img.path.clone();
                let url_clone = url.clone();
                let model_clone = model.clone();

                let result = crate::db_core::vision::analyze_image(
                    std::path::Path::new(&path),
                    &url_clone,
                    &model_clone,
                )
                .await;

                if cancel_token.is_cancelled() {
                    state.jobs.mark_cancelled(&job_id);
                    state.jobs.persist_terminal(&job_id, &state.db);
                    return;
                }

                match result {
                    Ok(fields) => {
                        let _ = state.db.store_vision_metadata(image_id, &model, &fields);
                        analyzed += 1;
                    }
                    Err(e) => crate::safe_eprintln!("Vision error for {}: {}", image_id, e),
                }
                state
                    .jobs
                    .update_progress(&job_id, (i + 1) as u32, Some(image_id));
                let _ = app.emit(
                    "vision-progress",
                    serde_json::json!({"current": i + 1, "total": total, "model": model}),
                );
            }

            state.jobs.complete(&job_id);
            state.jobs.persist_terminal(&job_id, &state.db);
            let _ = app.emit("job-status-changed", serde_json::json!({"job_id": &job_id, "status": "completed", "processed": analyzed}));
        });

        serde_json::json!({"job_id": job_id_ret, "total_images": total}).to_string()
    }
}

pub(super) fn router() -> super::ToolRouter<super::CullMcp> {
    super::CullMcp::vision_router()
}
