// Copyright (c) 2026-present Gleb Kalinin. Architecture and design by author.
// Implementation assisted by Claude (Anthropic). See AUTHORSHIP.md.

//! Track C3 valve evidence: the `cull-publish` proof plugin installs from a
//! registry document end-to-end. This is the machine-checkable version of
//! "proof plugin installable from registry end-to-end" — it consumes the
//! committed fixture registry (`tests/fixtures/plugin-registry/registry.json`,
//! regenerated by `scripts/build-plugin.mjs`) and the committed source bytes
//! at `plugins/cull-publish/entry.mjs`, never the network.

#![cfg(test)]

use super::{install, invoke, loader, registry};
use crate::commands::static_publishing::StaticPublishServerState;
use crate::db_core::db::Database;
use crate::db_core::detection::DetectionEngine;
use crate::db_core::embeddings::EmbeddingEngine;
use crate::db_core::secrets::MemoryStore;
use crate::services::{tokens, ServiceContext};
use crate::{services, watcher, AppState};
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("src-tauri has a parent repo root")
        .to_path_buf()
}

fn test_state() -> (AppState, tempfile::TempDir) {
    let tmp = tempfile::tempdir().unwrap();
    let db = Database::open(&tmp.path().join("test.db")).unwrap();
    let app_data_dir = tmp.path().join("app-data");
    let model_dir = tmp.path().join("models");
    std::fs::create_dir_all(&app_data_dir).unwrap();

    let state = AppState {
        db,
        app_data_dir,
        embedding_engine: parking_lot::Mutex::new(EmbeddingEngine::new(&model_dir)),
        detection_engine: parking_lot::Mutex::new(DetectionEngine::new_yolo(&model_dir)),
        safety_engine: parking_lot::Mutex::new(DetectionEngine::new_nudenet(&model_dir)),
        secrets: Box::new(MemoryStore::new()),
        jobs: services::jobs::JobRegistry::default(),
        action_manager: services::undo::ActionManager::new(),
        file_watcher: parking_lot::Mutex::new(watcher::FileWatcher::new()),
        clipboard_monitor: parking_lot::Mutex::new(
            services::clipboard_monitor::ClipboardMonitorState::default(),
        ),
        static_publish_server: parking_lot::Mutex::new(StaticPublishServerState::default()),
        preview_state: crate::preview::state::PreviewStateStore::default(),
        preview_web_stream: crate::preview::web_stream::PreviewWebStreamController::default(),
        agent_snapshots: parking_lot::Mutex::new(
            services::agent_snapshots::AgentSnapshotRegistry::default(),
        ),
        agent_snapshot_requests: parking_lot::Mutex::new(std::collections::HashMap::new()),
    };
    (state, tmp)
}

/// The Day-4 valve's machine-checkable evidence, end to end on a fresh
/// app-data dir: fixture registry parses -> cull-publish entry found ->
/// bundle bytes resolve from the file:// download -> checksum-verified
/// install -> loader re-verifies and returns the real plugin source ->
/// manifest permissions are granted -> plugin_invoke succeeds for the
/// granted publish ops (with module_static_publishing OFF: plugin presence
/// is the gate) and every call is audit-logged -> uninstall cleans up files
/// and grants.
#[test]
fn proof_plugin_cull_publish_installs_end_to_end() {
    let root = repo_root();

    // 1. Fetch the fixture registry (what `fetch_plugin_registry` does with
    //    a file:// `plugin_registry_url`).
    let registry_json =
        std::fs::read_to_string(root.join("tests/fixtures/plugin-registry/registry.json"))
            .expect("fixture registry must exist (run: node scripts/build-plugin.mjs)");
    let parsed = registry::parse_registry(&registry_json).expect("fixture registry must parse");
    assert!(
        parsed.warnings.is_empty(),
        "fixture registry must have no skipped entries: {:?}",
        parsed.warnings
    );

    // 2. Find cull-publish and check the manifest the user consents to.
    let entry = parsed
        .plugins
        .iter()
        .find(|p| p.manifest.id == "cull-publish")
        .expect("registry must list cull-publish");
    assert_eq!(
        entry.manifest.permissions,
        vec!["library:read", "export:read", "module:static-publishing"],
        "permissions are exactly what the publish UI needs"
    );
    assert_eq!(entry.manifest.entry, registry::INSTALLED_ENTRY);

    // 3. Resolve the bundle bytes from the file:// download (repo-relative,
    //    resolved against the repo root like the command layer's fixture
    //    escape hatch).
    let download_path = entry
        .download
        .strip_prefix("file://")
        .expect("fixture download is file://");
    let bundle =
        std::fs::read(root.join(download_path)).expect("committed plugin source must exist");
    let source = String::from_utf8(bundle.clone()).unwrap();
    assert!(
        source.contains("export_static_publish_package"),
        "bundle is the real publish UI, not a stub"
    );

    // 4. Install into a fresh app-data dir: checksum verify + grants.
    let (state, tmp) = test_state();
    let ctx = ServiceContext::from_app_state(&state, None);
    let plugins_dir = loader::plugins_dir(&state.app_data_dir);
    install::install_plugin_from_bytes(
        &ctx,
        &plugins_dir,
        &entry.manifest,
        &bundle,
        env!("CARGO_PKG_VERSION"),
    )
    .expect("registry install must succeed");

    // 5. The C1 loader loads it back (load-time re-hash passes) and the
    //    manifest permissions were granted.
    let loaded =
        loader::load_plugin_bundle(&plugins_dir, "cull-publish", env!("CARGO_PKG_VERSION"))
            .expect("installed plugin must load");
    assert_eq!(loaded.source, source);
    assert_eq!(loaded.manifest, entry.manifest);
    assert_eq!(
        state
            .db
            .granted_plugin_capabilities("cull-publish")
            .unwrap(),
        vec!["export:read", "library:read", "module:static-publishing"]
    );

    // 6. The granted publish ops succeed through plugin_invoke — exactly the
    //    sequence the plugin's Build-package control runs — with the
    //    module_static_publishing setting OFF (plugin presence is the gate).
    let source_path = tmp.path().join("proof.png");
    let image: image::RgbImage = image::ImageBuffer::from_pixel(48, 32, image::Rgb([32, 96, 160]));
    image.save(&source_path).unwrap();
    let image_id =
        crate::db_core::import::import_file(&state.db, &source_path, &state.app_data_dir)
            .unwrap()
            .unwrap();
    let collection_id = state.db.create_collection("Proof Set").unwrap();
    state
        .db
        .add_to_collection(&collection_id, &[image_id.as_str()])
        .unwrap();

    let collections = invoke::plugin_invoke_inner(&state, "cull-publish", "list_collections", None)
        .expect("library:read op must pass the bridge");
    assert_eq!(
        collections["collections"][0]["id"],
        serde_json::json!(collection_id)
    );

    let images = invoke::plugin_invoke_inner(
        &state,
        "cull-publish",
        "list_collection_images",
        Some(serde_json::json!({ "collection_id": collection_id })),
    )
    .expect("list_collection_images must pass the bridge");
    assert_eq!(images["count"], 1);

    let package = invoke::plugin_invoke_inner(
        &state,
        "cull-publish",
        "export_static_publish_package",
        Some(serde_json::json!({
            "canvas_name": "Proof Set",
            "items": [{ "image_id": image_id }],
            "layout_json": "{\"type\":\"plugin_collection_publish\"}",
            "output_dir": tmp.path().join("exports").to_string_lossy(),
            "include_thumbnails": true,
            "include_web": true,
            "include_full": false,
            "indexable": false,
            "links": [],
        })),
    )
    .expect("granted publish op must export a package");
    assert_eq!(package["image_count"], 1);
    assert!(Path::new(package["site_dir"].as_str().unwrap())
        .join("index.html")
        .exists());

    // 7. Everything is audit-logged with the plugin actor marker.
    let entries = tokens::get_recent_audit(&ctx, 10).unwrap();
    let logged: Vec<(&str, &str)> = entries
        .iter()
        .map(|e| (e.tool_name.as_str(), e.result_status.as_str()))
        .collect();
    assert!(logged.contains(&("plugin.install", "ok")));
    assert!(logged.contains(&("list_collections", "ok")));
    assert!(logged.contains(&("list_collection_images", "ok")));
    assert!(logged.contains(&("export_static_publish_package", "ok")));
    assert!(entries
        .iter()
        .all(|e| e.token_id.as_deref() == Some("plugin:cull-publish")));

    // 8. Uninstall cleans up: install dir gone, grants revoked, audited.
    install::uninstall_plugin(&ctx, &plugins_dir, "cull-publish").expect("uninstall must succeed");
    assert!(!plugins_dir.join("cull-publish").exists());
    assert!(state
        .db
        .granted_plugin_capabilities("cull-publish")
        .unwrap()
        .is_empty());
    let entries = tokens::get_recent_audit(&ctx, 1).unwrap();
    assert_eq!(entries[0].tool_name, "plugin.remove");
    assert_eq!(entries[0].result_status, "ok");
}

/// The committed fixture must stay in sync with the committed source: the
/// registry checksum describes the exact bytes that install into the manifest
/// entry path. Fails when entry.mjs changes without re-running
/// `node scripts/build-plugin.mjs`.
#[test]
fn proof_plugin_fixture_checksum_matches_committed_bundle() {
    let root = repo_root();
    let registry_json =
        std::fs::read_to_string(root.join("tests/fixtures/plugin-registry/registry.json")).unwrap();
    let parsed = registry::parse_registry(&registry_json).unwrap();
    let entry = &parsed.plugins[0];

    let bundle = std::fs::read(root.join(entry.download.strip_prefix("file://").unwrap())).unwrap();
    assert_eq!(
        format!("sha256:{}", install::sha256_hex(&bundle)),
        entry.manifest.checksum,
        "stale fixture: re-run `node scripts/build-plugin.mjs cull-publish`"
    );

    let entry_source = std::fs::read(root.join("plugins/cull-publish/entry.mjs")).unwrap();
    assert_eq!(
        install::sha256_hex(&entry_source),
        install::sha256_hex(&bundle),
        "fixture download is out of date with entry.mjs: re-run the build script"
    );
}
